# Generated by Django 2.0.4 on 2018-05-03 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupons', '0007_auto_20151105_2328'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='user_limit',
            field=models.PositiveIntegerField(default=1, help_text='Amount of users who can redeem this coupon. Set to 0 for unlimited', verbose_name='User limit'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='value',
            field=models.DecimalField(decimal_places=2, help_text='Arbitrary coupon value', max_digits=64, verbose_name='Value'),
        ),
    ]
